### PR TITLE
Make templates requirable   

### PR DESCRIPTION
**Pull request by anthonyshort**
This allows everything within the `templates` array to be required in the js using the name of the file.

```
{
   "name": "foo",
   "scripts": ["index.js"],
   "templates": ["template.html"]
}
```

```
var template = require('template.html')
```

As discussed in [issue 351](https://github.com/component/component/issues/351)

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
nice!

**Comment by timoxley** [comment]
+1 +1 +1

**Comment by lancejpollard** [comment]
+1

**Comment by tj** [comment]
sweet! sorry for the delay, thanks for the clean patch :D

**Comment by matthewmueller** [comment]
This should probably only work on .html files. If you want to use different templating systems with plugins they will get overwritten with `string-to-js`.

**Pull request merged**
