### PR TITLE
Normalize URLs

### PR DESCRIPTION
**Pull request by lepture**
Make the url beautiful, without `.`

### CODE REVIEW

**Comment by jonathanong** [comment]
there's also this related PR: https://github.com/component/builder.js/pull/119

**Comment by lepture** [comment]
@jonathanong it's 3 months ago, I wonder why it is not merged.

**Comment by jonathanong** [comment]
hmmm. for some reason i thought there were more special cases to add but i guess not. 

either way, we're probably better off using `url.resolve()` instead of these crazy `.replace(/\\/g, '/')` and `.join('/')` shenanigans.

**Comment by lepture** [comment]
@jonathanong Actually, url.resolve is not beautiful enough, for example:

```
url.resolve('///', 'a')
=> ///a
```

However, path.normalize will:

```
path.normalize('///')
=> /
```

**Comment by jonathanong** [comment]
why would that ever happen in the builder? if you can think of a test case for it, i'll fix it.

**Pull request closed without merging**
