### PR TITLE
Add a configuration to copy files instead of symlink

### PR DESCRIPTION
**Pull request by camshaft**
This PR improves #68 by adding the ability to copy files though the similar mechanism as setting a builder in dev mode.

### CODE REVIEW

**Comment by ghost** [comment]
Even better, +100. @CamShaft, so PR to component/component to add the copy option?

**Comment by ForbesLindesay** [comment]
This is 100% better.  +1 from me.

**Comment by camshaft** [comment]
Thanks guys!

**Comment by tj** [comment]
great stuff thanks man

**Comment by camshaft** [comment]
@visionmedia No problem. Awesome work on component!

**Comment by ghost** [comment]
Nice!!

**Pull request merged**
