### PR TITLE
Support for other script types

### PR DESCRIPTION
**Pull request by ghost**
This ensures aliases aren't lost when using script hooks e.g coffee-script.

### CODE REVIEW

**Comment by tj** [comment]
I dont get what this does, it should be pretty much the same technique as translating a template to a require()able script https://github.com/component/component.io/blob/master/lib/build/templates.js

**Comment by ghost** [comment]
Currently, aliases are built from `scripts` property and so you have to re-implement `.buildAliases` when you are using a transpiler for coffee-scripts etc.

**Comment by tj** [comment]
ah i see, if you're not using the .scripts array? hmm yeah tough call, would be nice if we made that easier to call from plugins, not a huge deal to check extnames in .scripts instead but yea hmm

**Comment by ghost** [comment]
yeah, plugins should definitely be able to add aliases easily.

**Pull request closed without merging**
