### PR TITLE
Async alias builder

### PR DESCRIPTION
**Pull request by bjornstar**
And bump batch version to v0.5
And cache configs on the root builder.

### CODE REVIEW

**Comment by bjornstar** [comment]
A little background on this issue. I was having problems with "too many files open" on one of my projects - #66 :cry:

Since this project uses batch I thought I'd just bump the batch version number and see if that solved my problem.

It got rid of the "too many open files" problem and replaced it with callbacks never getting called :cactus:

It turns out that batch silently fails when the maximum call stack size is exceeded. :angry: 

So, I wrapped the recursive calls in buildAliases in a process.nextTick to avoid the issue. You should really fix this in batch, though.

**Comment by jonathanong** [comment]
why not just open a PR or issue in batch?

**Comment by bjornstar** [comment]
Because it still needs to be fixed here and I have no idea what requirements batch has. At least this is node only and I don't have to worry about process.nextTick not existing.

**Comment by jonathanong** [comment]
@visionmedia plz fix batch :D

**Comment by tj** [comment]
dont need aliases anymore

**Pull request closed without merging**
