### PR TITLE
rework

### PR DESCRIPTION
**Pull request by yields**
sorry about that huge diff, i squashed all commits into one :s

this pull request aims to simplify the builder by pulling all of `component.json` and some sources `templates, scripts, styles, json`, plugins can now loop the components and remove / add / change them.

a couple of notes:
- i didn't remove aliases, i guess we can do that later on when we add `semver` support.
- i tested this on some apps and huge components, everything seems to work.
- i didn't trust the `repo:`  field because some components have incorrect one and some don't even have it.
- i know @ianstormtaylor have some suggestions for shortcuts ? maybe `.scripts(fn)`.

here is how you build a simple component with `scripts: [...]`

``` js
builder(__dirname)
  .use(builder.commonjs('scripts')) // => wraps all scripts in `require.register(...)`
  .use(builder.concat('scripts')) // => concats all `scripts`
  .build(function(err, build){
     var js = build.requirejs;
     js += build.scripts;
     js += build.aliases;
     write('out.js', js);
  });
```

/cc @visionmedia

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
sexy. yeah i think it would be nice to get some shortcuts in there for the common tasks, because lots of the builder use cases are just wanted to do some stuff _after_ the build and not necessarily tweak the plugin config. would be really easy to add shortcuts for the common ones. i can even do that myself once this is on a branch i have access to

i'm wondering if we shouldnt put this in master right away, maybe put it in `#1.0` and then we can fix a few more things and then merge to master. just because i think we need a few more things like template stringifying support? and json support? (natively with plugins i assume) and then because i think most people will need the `.scripts` shortcuts to get stuff done easily. but could easily be convinced to just do it live, and fast :)

really cool api though

`lookup` could also be renamed to `resolver` i think, but i cna make those changes myself in another pull since its all internal anyways for now

**Comment by jonathanong** [comment]
i like how stuff is split up. i had trouble understanding the source code before.

why does commonjs need to be separated? is there an instance when it wouldn't be used?

**Comment by jonathanong** [comment]
also, i'd like two plugin examples (since i'm not totally sure how it works):
- filter `.coffee` files from `.scripts`, covert them to js, concat
- read blobs from `.blobs`, convert them to an `ArrayBuffer` in js, concat

**Comment by jonathanong** [comment]
btw this is half of what the resolver is supposed to accomplish. you can loop through and add/remove/change components before it even touches the builder

**Comment by yields** [comment]
@ianstormtaylor 

i personally think this should be merged to master, the only thing that is changed is the api not the output [json and templates](https://github.com/yields/builder.js/blob/313e52fa1988d538b2da0786f717cc0a5b84863c/test/commonjs.js#L26-L50) are supported. i tested it on analytics.js and some more components / apps i have and everything works as expected.

it's very likely i've missed something and there are bugs, but i don't think this shouldn't be merged ;)

@jonathanong 

> why does commonjs need to be separated? is there an instance when it wouldn't be used?

because someone might have his own require implementation.

> btw this is half of what the resolver is supposed to accomplish

yeah just to avoid confusion: this pull request doesn't aim to add features it just aims to change the api, the output should be the same as `builder.js#0.10.0`.

**Comment by jonathanong** [comment]
When we move to a resolver, I don't see the point of supporting different require implementations since people might as well just create their own builder. Especially builder2's require implementation whose logic is mostly implemented in the builder itself. Thus I don't see the point of supporting it now.

This is going to piss off coffee script people in the meantime, huh?

**Comment by ianstormtaylor** [comment]
@yields sold! haha

**Comment by yields** [comment]
> I don't see the point of supporting different require implementations since people might as well just create their own builde

well, the reason i refactored the builder was because i wanted to wrap `require.register()` which wasn't possible with the old builder, so i just created my own builder :P

if this is merged i can just do:

``` js
builder('something')
  .use(commonjs('scripts'))
  .use(wrapthem())
  .use(concat('scripts'))
  .build(fn);
```

> This is going to piss off coffee script people in the meantime, huh?

coffee script people can use plugins ? if you're confused about how they work  i can add some examples whenever this is merged.

**Comment by jonathanong** [comment]
what did you want to do with youre requirejs implementation? i want to see how i can improve what i have right now.

i meant due to the API change. i'm assuming the older plugins won't work (though they are trivial to reimplement). people are going to pissed if they update to component 0.20 and their plugins don't work immediately, especially since they don't pin (i don't pin component either). i don't personally care though haha

**Comment by ianstormtaylor** [comment]
id assume they are pinning component tbh since it defaults to being pinned when installed. ideally this would be a major bump, but we dont really want to give it the 1.0 seal

**Comment by ericgj** [comment]
Looks super. But I think an announcement on the component list would be a good idea to give people some time to update their old builder plugins (AKA hacks)....

Also what about getting the tests to pass before release? Haven't looked too closely but it seems a bunch could be removed since they deal with old builder internals. The rest should be pretty easy to reimplement.  I could help with this.

**Comment by tj** [comment]
LMK when it's good to merge. I definitely agree that the require() part is all just implementation details so I don't really see people replacing that, but it doesn't hurt much either

**Comment by tj** [comment]
mmmmeeerged

**Comment by ianstormtaylor** [comment]
http://www.youtube.com/watch?v=Y1PVmANeyAg

**Pull request merged**
