### PR TITLE
Option to avoid symlinks

### PR DESCRIPTION
**Pull request by ghost**
Enables copying of images and files instead of symlinking them to /build if the 'COPY' variable in the user environment is set to true. This helps avoid problems in environments where symlinks aren't applicable. E.g. to use this with component build, one runs `COPY=true component build`.

### CODE REVIEW

**Comment by camshaft** [comment]
I would prefer it to be an option passed similar to `-d, --development`. This way we're not having to mix env vars and options.

**Comment by ghost** [comment]
yeah, but what if you want to 'only' use builder e.g. https://github.com/component/builder.js/pull/68/files#L2R173 ?

**Comment by ForbesLindesay** [comment]
:+1: for functionality :-1: for environment vars.  If you want to only use builder, pass builder the option.  We already support `builder.development()` to put it into development mode so just support `builder.copyFiles()`

**Comment by ghost** [comment]
@ForbesLindesay ever pushed a repo with components to github pages?

**Comment by ForbesLindesay** [comment]
I'm not sure, what does that have to do with anything.  I don't think I've done so with a component that has files like images etc.

I agree we need a way to do it.  But it shouldn't be as an environment variable.  component-builder is a library, and on the whole you should leave environment variables as an application level thing.  Just implement it in the same way as command line flags like `--development` are implemented in `component build`

**Comment by camshaft** [comment]
@ForbesLindesay @kelonye check out #69

**Comment by ghost** [comment]
Closing in favor of #69

**Pull request closed without merging**
